name: Greetings

on:
  pull_request_target:
  issues:

jobs:
  greet-first-time-contributor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      # Greet users on their first issue or PR
      - name: Greet first-time contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hey there! Thanks for opening your first issue with us.
            We appreciate your contribution and will get back to you shortly.
            
            In the meantime, please make sure you've followed our issue guidelines.
          pr-message: |
            🚀 Thanks for submitting your first pull request!  
            We’re excited to review it and help you get it merged.

            Please ensure you've signed the CLA (if applicable) and that all tests pass.
